# Site settings
baseURL = "https://anypaste.xyz/"
languageCode = "en-us"
title = "Anypaste - Smart command-line file sharing tool for Linux and Mac"
theme = "simpledoc"

# Top menu
[[menu.top]]
    name = "hugo-simpledoc-theme GitHub Repository"
    weight = 20
    url = "https://github.com/aerohub/hugo-simpledoc-theme"
[[menu.top]]
    name = "Hugo - A Fast and Flexible Website Generator"
    weight = 10
    url = "http://gohugo.io/"
[[menu.top]]
    name = "Original WPThemeDoc by Rich Tabor"
    weight = 30
    url = "https://github.com/richtabor/WPThemeDoc"

# Site parameters
[params]
    landingTitle = "Anypaste"

    # Meta
    description = "Anypaste automatically determines the best host for your files and uploads them in a single command. File path in, URL out."
    author = "Mark Polyakov"
    keywords = "imgur, gfycat, command line, cli, file sharing, pastebin, linux, mac, automatic"
    
    # Header
    # If not set, site title and meta description will be shown.
    # You may use markdown here
    headerTitle = "Documentation"
    headerDescription = "How to use and make plugins for Anypaste."
    
    # Back-to-top button name
    bttButton = ""

[params.asciinema]
    id = "RceX2cd4ELhocM36I5mSHJycv"
    rows = 25
